version: "3"
services:
  portgres:
    image: "postgres:latest"
    container_name: postgres
    env_file:
      - .env.development

  redis:
    image: "redis:latest"
    container_name: redis
    env_file:
      - .env.development

  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    container_name: server
    env_file:
      - .env.development
    volumes:
      - /home/node/app/node_modules
      - ./server:/home/node/app
