name: multi container docker
on:
  push:
    branch: main

jobs:
  build_react_app:
    name: build client container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t calebfreitas/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true calebfreitas/react-test npm test

  build_remaining_containers:
    name: build remaining containers after tests succeed
    needs: build_react_app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t calebfreitas/multi-client ./client
      - run: docker build -t calebfreitas/multi-nginx ./nginx
      - run: docker build -t calebfreitas/multi-server ./server
      - run: docker build -t calebfreitas/multi-worker ./worker

      - run: docker push calebfreitas/multi-client
      - run: docker push calebfreitas/multi-nginx
      - run: docker push calebfreitas/multi-server
      - run: docker push calebfreitas/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-container-docker
          environment_name: Multicontainerdocker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-023596404588
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip